steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-east4-docker.pkg.dev/ultmt-app-e2e/ultmt-services/stall-one', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-east4-docker.pkg.dev/ultmt-app-e2e/ultmt-services/stall-one']
options:
  logging: CLOUD_LOGGING_ONLY