export const GENERIC_ERROR = 'We are unable to perform this operation. Please try again later.'
export const UNAUTHENTICATED_USER = 'This user is unauthenticated to perform this action'
export const UNABLE_TO_FETCH_TEAM = 'We were unable to get data for this team'
export const WRONG_RESOLVE_CODE = 'This is not the correct code to join the game.'
export const UNABLE_TO_FIND_GAME = 'We are unable to find this game.'
